config/routes.rb
  resources :includes
  get 'account/includes/new', to: 'includes#new', as: :include_new
  get 'account/includes/:id/edit', to: 'includes#edit', as: :include_edit
  get 'account/includes/:id/destroy', to: 'includes#delete_include', as: :delete_include

  resources :codesubs
  get 'account/codesubs/new', to: 'codesubs#new', as: :codesub_new
  get 'account/codesubs/:id/edit', to: 'codesubs#edit', as: :codesub_edit
  get 'account/codesubs/:id/destroy', to: 'codesubs#delete_codesub', as: :delete_codesub

  resources :softopens
  get 'account/softopens/new', to: 'softopens#new', as: :softopen_new
  get 'account/softopens/:id/edit', to: 'softopens#edit', as: :softopen_edit
  get 'account/softopens/:id/destroy', to: 'softopens#delete_softopen', as: :delete_softopen

  resources :industries
  get 'account/industries/new', to: 'industries#new', as: :industry_new
  get 'account/industries/:id/edit', to: 'industries#edit', as: :industry_edit
  get 'account/industries/:id/destroy', to: 'industries#delete_industry', as: :delete_industry

  resources :softopen3ds
  get 'account/softopen3ds/new', to: 'softopen3ds#new', as: :softopen3d_new
  get 'account/softopen3ds/:id/edit', to: 'softopen3ds#edit', as: :softopen3d_edit
  get 'account/softopen3ds/:id/destroy', to: 'softopen3ds#delete_softopen3d', as: :delete_softopen3d

  resources :modelsubs
  get 'account/modelsubs/new', to: 'modelsubs#new', as: :modelsub_new
  get 'account/modelsubs/:id/edit', to: 'modelsubs#edit', as: :modelsub_edit
  get 'account/modelsubs/:id/destroy', to: 'modelsubs#delete_modelsub', as: :delete_modelsub

  resources :genres
  get 'account/genres/new', to: 'genres#new', as: :genre_new
  get 'account/genres/:id/edit', to: 'genres#edit', as: :genre_edit
  get 'account/genres/:id/destroy', to: 'genres#delete_genre', as: :delete_genre

   resources :encodes
  get 'account/encodes/new', to: 'encodes#new', as: :encode_new
  get 'account/encodes/:id/edit', to: 'encodes#edit', as: :encode_edit
  get 'account/encodes/:id/destroy', to: 'encodes#delete_encode', as: :delete_encode

  resources :latars
  get 'account/latars/new', to: 'latars#new', as: :latar_new
  get 'account/latars/:id/edit', to: 'latars#edit', as: :latar_edit
  get 'account/latars/:id/destroy', to: 'latars#delete_latar', as: :delete_latar

  resources :vidsubs
  get 'account/vidsubs/new', to: 'vidsubs#new', as: :vidsub_new
  get 'account/vidsubs/:id/edit', to: 'vidsubs#edit', as: :vidsub_edit
  get 'account/vidsubs/:id/destroy', to: 'vidsubs#delete_vidsub', as: :delete_vidsub

  resources :framerates
  get 'account/framerates/new', to: 'framerates#new', as: :framerate_new
  get 'account/framerates/:id/edit', to: 'framerates#edit', as: :framerate_edit
  get 'account/framerates/:id/destroy', to: 'framerates#delete_framerate', as: :delete_framerate

  resources :aeplugins
  get 'account/aeplugins/new', to: 'aeplugins#new', as: :aeplugin_new
  get 'account/aeplugins/:id/edit', to: 'aeplugins#edit', as: :aeplugin_edit
  get 'account/aeplugins/:id/destroy', to: 'aeplugins#delete_aeplugin', as: :delete_aeplugin

  resources :languages
  get 'account/languages/new', to: 'languages#new', as: :language_new
  get 'account/languages/:id/edit', to: 'languages#edit', as: :language_edit
  get 'account/languages/:id/destroy', to: 'languages#delete_language', as: :delete_language

  resources :conversations do 
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :notes
  get 'account/notes', to: 'accounts#note', as: :note_account
  get 'account/notes/:id/racoon', to: 'accounts#note_edit', as: :note_edit
  get 'account/destroy/:id', to: 'notes#a_destroy'
  get 'account/b_destroy/:note_id/:id', to: 'notes#b_destroy'
  get 'account/shared/:id', to: 'notes#shared'

  resources :vacancies
  resources :teams
  get 'account/teams/data/new', to: 'teams#new', as: :team_account
  get 'account/teams/data/:id', to: 'teams#edit', as: :team_edit
  get 'account/teams/:id/destroy', to: 'teams#delete_team'
  get 'account/teams/data/:id/members', to: 'teams#show', as: :show_team
  get 'account/products/all_themes/:themes', to: 'accounts#all_product', as: :all_themes
  get 'account/products/delete/:id', to: 'themes#delete_by_admin'
  get 'account/products/all_codes/:codes', to: 'accounts#all_product', as: :all_codes
  get 'account/products/delete_code/:id', to: 'codes#delete_by_admin'
  get 'account/products/all_graphics/:graphics', to: 'accounts#all_product', as: :all_graphics
  get 'account/products/delete_graphic/:id', to: 'graphics#delete_by_admin'
  get 'account/products/all_t3ds/:t3ds', to: 'accounts#all_product', as: :all_t3ds
  get 'account/products/delete_t3d/:id', to: 't3ds#delete_by_admin'
  get 'account/products/all_videofxes/:videofxes', to: 'accounts#all_product', as: :all_videofxes
  get 'account/products/delete_videofx/:id', to: 'videofxes#delete_by_admin'
  get 'account/products/all_fonts/:fonts', to: 'accounts#all_product', as: :all_fonts
  get 'account/products/delete_font/:id', to: 'fonts#delete_by_admin'
  get 'account/products/all_courses/:courses', to: 'accounts#all_product', as: :all_courses
  get 'account/products/delete_course/:id', to: 'courses#delete_by_admin'

  get 'account/transaction/order/completed', to: 'accounts#order', as: :data_order
  get 'account/transaction/data_1/:week/order/completed', to: 'accounts#order', as: :data_order_week
  get 'account/transaction/data_2/:day/order/completed', to: 'accounts#order', as: :data_order_day
  get 'account/transaction/data_3/:month/order/completed', to: 'accounts#order', as: :data_order_month

  get 'account/vacancies/data_1/:programmer', to: 'accounts#all_vacancy', as: :all_vacancy_programmer
  get 'account/vacancies/data_2/:designer', to: 'accounts#all_vacancy', as: :all_vacancy_designer
  get 'account/vacancies/data_3/:animator', to: 'accounts#all_vacancy', as: :all_vacancy_animator
  get 'account/vacancies/data_4/:network', to: 'accounts#all_vacancy', as: :all_vacancy_network
  get 'account/items', to: 'accounts#free_item', as: :free_item
  get 'account/items/:id', to: 'accounts#free_destroy', as: :destroy_free
  get 'vacancies/data/search', to: 'vacancies#search_vacancy', as: :vacancies_search
  
  #freeitem

  get 'themes/freeitem/:id', to: 'themes#free_theme'
  get 'codes/freeitem/:id', to: 'codes#free_code'
  get 'graphics/freeitem/:id', to: 'graphics#free_graphic'
  get 't3ds/freeitem/:id', to: 't3ds#free_t3d'
  get 'videofxes/freeitem/:id', to: 'videofxes#free_videofx'
  get 'fonts/freeitem/:id', to: 'fonts#free_font'
  get 'courses/freeitem/:id', to: 'courses#free_course'

  get 'delete/carts/:id', to: 'line_items#delete', as: :line_items_delete
  
  get 'themes/:id/upload', to: 'themes#upload', as: :upload
  get 'codes/:id/upload', to: 'codes#upload', as: :upload_code
  get 'graphics/:id/upload', to: 'graphics#upload', as: :upload_graphic
  get 't3dreams/:id/upload', to: 't3ds#upload', as: :upload_t3d
  get 'videofxes/:id/upload', to: 'videofxes#upload', as: :upload_videofx
  get 'fonts/upload', to: 'fonts#new'
  get 'courses/:id/upload', to: 'courses#upload', as: :upload_course
  get 'courses/:id/curriculum', to: 'courses#manage_course', as: :manage_course

  get 'themes/item/:id', to: 'themes#item', as: :item
  get 'codes/item/:id', to: 'codes#item', as: :item_code
  get 'graphics/item/:id', to: 'graphics#item', as: :item_graphic
  get 't3dreams/item/:id', to: 't3ds#item', as: :item_t3d
  get 'videofxes/item/:id', to: 'videofxes#item', as: :item_videofx
  get 'fonts/item/:id', to: 'fonts#item', as: :item_font
  get 'courses/item/:id', to: 'courses#item', as: :item_course

  get 'themes/item/:id/screenshot', to: 'themes#screenshot', :as => :screenshot
  get 'codes/item/:id/screenshot', to: 'codes#screenshot', :as => :screenshot_code
  get 'graphics/item/:id/screenshot', to: 'graphics#screenshot', :as => :screenshot_graphic
  get 't3dreams/item/:id/screenshot', to: 't3ds#screenshot', :as => :screenshot_t3d
  get 'videofxes/item/:id/screenshot', to: 'videofxes#screenshot', :as => :screenshot_videofx
  get 'fonts/item/:id/screenshot', to: 'fonts#screenshot', :as => :screenshot_font

  get 'themes/aprroved/:id/theme', to: 'themes#success_reviewer', as: :success_reviewer
  get 'codes/aprroved/:id/code', to: 'codes#success_reviewer', as: :cdsuccess_reviewer
  get 't3dreams/aprroved/:id/t3dream', to: 't3ds#success_reviewer', as: :t3success_reviewer
  get 'videofxes/aprroved/:id/videofx', to: 'videofxes#success_reviewer', as: :vsuccess_reviewer
  get 'fonts/aprroved/:id/font', to: 'fonts#success_reviewer', as: :fsuccess_reviewer
  get 'courses/aprroved/:id/course', to: 'courses#success_reviewer', as: :cvsuccess_reviewer
  get 'graphics/aprroved/:id/graphic', to: 'graphics#success_reviewer', as: :gsuccess_reviewer

  get 'themes/reject/:id/theme', to: 'themes#reject_reviewer', as: :treject_reviewer
  get 'codes/reject/:id/code', to: 'codes#reject_reviewer', as: :creject_reviewer
  get 't3dreams/reject/:id/t3dream', to: 't3ds#reject_reviewer', as: :t3reject_reviewer
  get 'videofxes/reject/:id/videofx', to: 'videofxes#reject_reviewer', as: :vreject_reviewer
  get 'fonts/reject/:id/font', to: 'fonts#reject_reviewer', as: :freject_reviewer
  get 'courses/reject/:id/course', to: 'courses#reject_reviewer', as: :cvreject_reviewer
  get 'graphics/reject/:id/graphic', to: 'graphics#reject_reviewer', as: :greject_reviewer

  resources :users, only: [:create, :edit, :update] do
    resources :collections, only: [:new, :create, :edit, :update, :destroy, :show]
    resources :contacts, only: [:new, :create] 
    resources :withdrawals, only: [:create, :update]
  end
  get 'account/:user_id/wishlist/:id/wishitem', to: 'collections#show', as: :show_collection
  # resources :collections, only: [:destroy]
  get 'sign_up', to: 'users#sign_up', as: :sign_up
  get 'account/:id/profile/edit', to: 'users#edit', as: :profile
  resources :sessions, only: [:new, :create, :destroy]
  get 'sign_in', to: 'sessions#new'

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :signed_in_user

  layout "account"

  def new

  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end


  private

  def message_params
    params.require(:message).permit(:body, :subject)
  end

  def conversation_params
    params.require(:conversation).permit(:subject, :body, recipients:[])
  end

end

app/views/conversations/_conversation.html.erb
<% index = conversation_counter %>
<div role="tabpanel" class="tab-pane fade <%= 'in active' if index == 0 %>" id="cover_<%= conversation.id %>"> 
  <%# conversation.receipts_for(current_user).each do |receipt| %>
    <%# message = receipt.message %>
    <div class="img_hdg pull-left">
      <%= image_tag conversation.originator.avatar_url(:thumb) %>
    </div>
    <div class="descye57">
      <p class="name"><%= conversation.originator.first_n.capitalize %> <%= conversation.originator.last_n.capitalize %> <span class="tgl"><%= conversation.messages.last.created_at.strftime("%b %d, %Y") %></span></p>
      <span class="full-ht"> <%= link_to conversation_path(conversation) do %><i class="fa fa-reply" aria-hidden="true"></i><% end %></span>
      <span class="to_">subject: <%#= conversation.subject.capitalize %> <%= conversation.subject.capitalize %> </span> 
    </div>
    <div class="comtent">
      <p class="subject_i">
      <p class="con_oo"i>
      <%= simple_format(conversation.messages.first.body) %>
      </p>
    </div>
  <%# end %>
</div>

app/views/conversations/_form.html.erb
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
  <div class="form-group hsdga5357">
    <%= f.select(:recipients, User.all.where(reviewer: true).collect {|p| [ p.username, p.id ] }, {}, { multiple: true , class: "chosen-select form-control reply_form" })%>
  </div>
  <div class="form-group hsdga5357">
    <%= f.text_field :subject, placeholder: "Subject", class: "form-control reply_form " %>
  </div>
  <div class="form-group hsdga5357">
    <%= f.text_area :body, class: 'form-control reply_form',placeholder: "Type your message here", rows: 4  %>

  </div>

  <%= f.submit "Send Message", class: "niywag" %>
<% end %>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
<% message = receipt.message %>
<div class="img_hdg pull-left">
  <%= image_tag message.sender.avatar_url(:thumb) %>
</div>
<div class="descye57">
  <p class="name"><%= message.sender.first_n.capitalize %> <%= message.sender.last_n.capitalize %> <span class="tgl"><%= message.created_at.strftime("%b %d, %Y") %></span></p>
  <span class="to_">subject: <%#= conversation.subject.capitalize %> <%= message.subject.capitalize %> </span> 
</div>
<div class="comtent relpiyi">
  <p class="subject_i">
  <p class="con_oo"i>
  <%= simple_format(message.body) %>
  </p>
</div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>
<script>
$('.aktif').removeClass();
$('.message').addClass('aktif');
</script>

app/views/conversations/show.html.erb
<%= title "Replies Messages ~ KHAPOO" %>

<div class="mail-nav">
  <div class="isi-menu-mail">
    <div class="title-mail">
      <div class="left-to pull-left">
        <p class="dgaji67">Mail</p>
        <% if unread_messages_count >= 1 %>
          <span class="dshgq1">You have <%= unread_messages_count %> unread email</span>
        <% elsif unread_messages_count <= 0 %>
          <span class="dshgq1">You have't email</span>
        <% end %>
      </div>
      <div class="right-to pull-right">
        <%= link_to "NEW MESSAGE", new_conversation_path, class: "new_email", "data-turbolinks": false %>
        <% if conversation.is_trashed?(current_user) %>
          <%= link_to 'UNTRASH', untrash_conversation_path(conversation), "data-turbolinks": false, class: 'new_email', method: :post %>
        <% else %>
          <%= link_to 'MOVE TO TRASH', trash_conversation_path(conversation), "data-turbolinks": false, class: 'new_email', style: "background-color: #d9534f; border-color: #d43f3a;", method: :post,
            data: {confirm: 'Are you sure?'} %>
        <% end %>
      </div>
      <div class="clear"></div>
    </div>

    <div class="menu-inbx">
      <div class="list-inline mnu-uli">
        <p class="mnu-f <%= active_page(:inbox) %>"><i class="fa fa-inbox" aria-hidden="true"></i><%= link_to "INBOX", mailbox_inbox_path, class: "inbox actig" %></p>
        <p class="mnu-f <%= active_page(:sent) %>"><i class="fa fa-paper-plane" aria-hidden="true"></i><%= link_to "SENT", mailbox_sent_path, class: "sent" %></p>
        <p class="mnu-f pempem <%= active_page(:trash) %>"><i class="fa fa-trash" aria-hidden="true"></i><%= link_to "TRASH", mailbox_trash_path, class: "trash" %></p>
      </div>
      <div class="clear"></div>
    </div>

    <div class="col-md-4 freak-left">
      <div class="seacbv">
        <input type="text" class="form-control schmail" placeholder="Search email here...">
      </div>
      <% mailbox.conversations.each_with_index do |conversation, index| %>
        <div class="receipt" role="tablist">
          <div class="balamed <%= 'active' if index == 0 %>">
            <%= link_to conversation_path(conversation), class: "djfgf" do  %>
              <div class="imgdf">
                <%= image_tag conversation.originator.avatar_url(:thumb) %>
              </div>
              <div class="condfer">
                <p class="name"><%= conversation.originator.first_n.capitalize %> <%= conversation.originator.last_n.capitalize %> <span class="pull-right"> <%= conversation.messages.last.created_at.strftime("%b %d, %Y") %></span></p>
                <p class="congst"><span class="subject"><%= conversation.subject.capitalize %> - </span> <%= truncate(conversation.messages.last.body, length: 20) %></p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
    
    <div class="col-md-8 freak-right">
      <%= render partial: 'messages' %>
      <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
        <div class="form-group hsdga5357">
          <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control reply_form" %>
        </div>
        <%= f.submit "Reply", class: 'btn btn-danger pull-right niywag' %>
      <% end %>
    </div>
    <div class="clear"></div>
  </div>
</div>
<script>
$('.aktif').removeClass();
$('.message').addClass('aktif');
</script>