config/routes.rb
Rails.application.routes.draw do
  post 'user/store/:id/follow_user', to: 'relationships#follow_user', as: :follow_user

  post 'user/store/:id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'user/delete/:id', to: 'users#delete_user'

  get 'password_resets/new'

  get 'password_resets/edit'

  mount ActionCable.server => '/cable'

  resources :home, only: [:index]
  #themes routes
  resources :themes do
    resources :comments
    resources :reviews, only: [:create]
    member do
      get 'screenshot/:screenshot_id/delete', to: 'themes#delete_screenshot', as: :delete_screenshot
      get 'broke/:broke_id/delete', to: 'themes#delete_broke', as: :delete_broke
      get :theme_suka, to: 'themes#theme_suka'
      get :theme_unsuka, to: 'themes#theme_unsuka'
      get :delete_theme, to: 'themes#delete_theme'
      put :like, to: 'themes#upvote'
      put :dislike, to: 'themes#downvote'
    end
  end

  get 'themes/this/:recent', to: 'themes#index', as: :themes_recent
  get 'themes/that/:recoms', to: 'themes#index', as: :themes_recoms

  resources :codes do
    resources :comments
    resources :reviews, only: [:create]
    member do 
      get 'screenshot/:screenshot_id/delete', to: 'codes#delete_screenshot', as: :delete_cdscreenshot
      get 'broke/:broke_id/delete', to: 'codes#delete_broke', as: :delete_cdbroke
      get :delete_code, to: 'codes#delete_code'
      get :code_suka, to: 'codes#code_suka'
      get :code_unsuka, to: 'codes#code_unsuka'
      put :like, to: 'codes#upvote'
      put :dislike, to: 'codes#downvote'
    end
  end

  get 'codes/this/:recent', to: 'codes#index', as: :codes_recent
  get 'codes/that/:recoms', to: 'codes#index', as: :codes_recoms

  resources :graphics do
    resources :comments
    resources :reviews, only: [:create]
    member do 
      get 'screenshot/:screenshot_id/delete', to: 'graphics#delete_screenshot', as: :delete_ghscreenshot
      get 'broke/:broke_id/delete', to: 'graphics#delete_broke', as: :delete_ghbroke
      get 'delete_graphic', to: 'graphics#delete_graphic'
      get :graphic_suka, to: 'graphics#graphic_suka'
      get :graphic_unsuka, to: 'graphics#graphic_unsuka'
      put :like, to: 'graphics#upvote'
      put :dislike, to: 'graphics#downvote'
    end
  end

  get 'graphics/this/:recent', to: 'graphics#index', as: :graphics_recent
  get 'graphics/that/:recoms', to: 'graphics#index', as: :graphics_recoms

  resources :t3ds do
    resources :comments
    resources :reviews, only: [:create]
    member do
      get 'screenshot/:screenshot_id/delete', to: 't3ds#delete_screenshot', as: :delete_t3screenshot
      get 'broke/:broke_id/delete', to: 't3ds#delete_broke', as: :delete_t3broke
      get :delete_t3d, to: 't3ds#delete_t3d'
      get :t3d_suka, to: 't3ds#t3d_suka'
      get :t3d_unsuka, to: 't3ds#t3d_unsuka'
      put :like, to: 't3ds#upvote'
      put :dislike, to: 't3ds#downvote'
    end
  end

  get 't3dreams/this/:recent', to: 't3ds#index', as: :t3ds_recent
  get 't3ds/that/:recoms', to: 't3ds#index', as: :t3ds_recoms

  resources :videofxes do
    resources :comments
    resources :reviews, only: [:create]
    member do 
      get 'videm/:videm_id/delete', to: 'videofxes#delete_videm', as: :delete_videm
      get 'broke/:broke_id/delete', to: 'videofxes#delete_broke', as: :delete_vbroke
      get :delete_videofx, to: 'videofxes#delete_videofx'
      get :video_suka, to: 'videofxes#video_suka'
      get :video_unsuka, to: 'videofxes#video_unsuka'
      put :like, to: 'videofxes#upvote'
      put :dislike, to: 'videofxes#downvote'
    end
  end
  get 't3dreams', to: 't3ds#index'
  get 't3dreams/new', to: 't3ds#new'
  get 'videofxes/this/:recent', to: 'videofxes#index', as: :videofxes_recent
  get 'videofxes/that/:recoms', to: 'videofxes#index', as: :videofxes_recoms

  resources :fonts do
    resources :comments
    resources :reviews, only: [:create]
    member do
      get 'screenshot/:screenshot_id/delete', to: 'fonts#delete_screenshot', as: :delete_ftscreenshot
      get 'broke/:broke_id/delete', to: 'fonts#delete_broke', as: :delete_ftbroke
      get :delete_font, to: 'fonts#delete_font'
      get :font_suka, to: 'fonts#font_suka'
      get :font_unsuka, to: 'fonts#font_unsuka'
      put :like, to: 'fonts#upvote'
      put :dislike, to: 'fonts#downvote'
    end
  end

  get 'fonts/this/:recent', to: 'fonts#index', as: :fonts_recent
  get 'fonts/that/:recoms', to: 'fonts#index', as: :fonts_recoms
  

   resources :courses do
    resources :comments
    resources :reviews, only: [:create]
    resources :headsecs do
      resources :lectures
    end
    member do
      get 'freepi/:freepi_id/delete', to: 'courses#delete_trailer', as: :delete_trailer
      get 'cofile/:cofile_id/delete', to: 'courses#delete_cofile', as: :delete_cofile
      get :delete_course, to: 'courses#delete_course'
      get :course_suka, to: 'courses#course_suka'
      get :course_unsuka, to: 'courses#course_unsuka'
      put :like, to: 'courses#upvote'
      put :dislike, to: 'courses#downvote'
    end
  end

  get 'courses/this/:recent', to: 'courses#index', as: :courses_recent
  get 'courses/that/:recoms', to: 'courses#index', as: :courses_recoms
  resources :akusukas, only: [:new, :create]
  resources :teams do
    resources :messagereviewers
  end

  resources :carts
  resources :line_items
  resources :payment_noties
  resources :categories
  get 'account/categories/new', to: 'categories#new', as: :category_new
  get 'account/categories/:id/edit', to: 'categories#edit', as: :category_edit
  get 'account/categories/:id/destroy', to: 'categories#delete_category', as: :delete_category

  resources :subcategories
  get 'account/subcategories/new', to: 'subcategories#new', as: :subcategory_new
  get 'account/subcategories/:id/edit', to: 'subcategories#edit', as: :subcategory_edit
  get 'account/subcategories/:id/destroy', to: 'subcategories#delete_subcategory', as: :delete_subcategory
  
  resources :browsers
  get 'account/browsers/new', to: 'browsers#new', as: :browser_new
  get 'account/browsers/:id/edit', to: 'browsers#edit', as: :browser_edit
  get 'account/browsers/:id/destroy', to: 'browsers#delete_browser', as: :delete_browser

  resources :dependencies
  get 'account/dependencies/new', to: 'dependencies#new', as: :dependency_new
  get 'account/dependencies/:id/edit', to: 'dependencies#edit', as: :dependency_edit
  get 'account/dependencies/:id/destroy', to: 'dependencies#delete_dependency', as: :delete_dependency

  resources :compatibles
  get 'account/compatibles/new', to: 'compatibles#new', as: :compatible_new
  get 'account/compatibles/:id/edit', to: 'compatibles#edit', as: :compatible_edit
  get 'account/compatibles/:id/destroy', to: 'compatibles#delete_compatible', as: :delete_compatible

  resources :includes
  get 'account/includes/new', to: 'includes#new', as: :include_new
  get 'account/includes/:id/edit', to: 'includes#edit', as: :include_edit
  get 'account/includes/:id/destroy', to: 'includes#delete_include', as: :delete_include

  resources :codesubs
  get 'account/codesubs/new', to: 'codesubs#new', as: :codesub_new
  get 'account/codesubs/:id/edit', to: 'codesubs#edit', as: :codesub_edit
  get 'account/codesubs/:id/destroy', to: 'codesubs#delete_codesub', as: :delete_codesub

  resources :softopens
  get 'account/softopens/new', to: 'softopens#new', as: :softopen_new
  get 'account/softopens/:id/edit', to: 'softopens#edit', as: :softopen_edit
  get 'account/softopens/:id/destroy', to: 'softopens#delete_softopen', as: :delete_softopen

  resources :industries
  get 'account/industries/new', to: 'industries#new', as: :industry_new
  get 'account/industries/:id/edit', to: 'industries#edit', as: :industry_edit
  get 'account/industries/:id/destroy', to: 'industries#delete_industry', as: :delete_industry

  resources :softopen3ds
  get 'account/softopen3ds/new', to: 'softopen3ds#new', as: :softopen3d_new
  get 'account/softopen3ds/:id/edit', to: 'softopen3ds#edit', as: :softopen3d_edit
  get 'account/softopen3ds/:id/destroy', to: 'softopen3ds#delete_softopen3d', as: :delete_softopen3d

  resources :modelsubs
  get 'account/modelsubs/new', to: 'modelsubs#new', as: :modelsub_new
  get 'account/modelsubs/:id/edit', to: 'modelsubs#edit', as: :modelsub_edit
  get 'account/modelsubs/:id/destroy', to: 'modelsubs#delete_modelsub', as: :delete_modelsub

  resources :genres
  get 'account/genres/new', to: 'genres#new', as: :genre_new
  get 'account/genres/:id/edit', to: 'genres#edit', as: :genre_edit
  get 'account/genres/:id/destroy', to: 'genres#delete_genre', as: :delete_genre

   resources :encodes
  get 'account/encodes/new', to: 'encodes#new', as: :encode_new
  get 'account/encodes/:id/edit', to: 'encodes#edit', as: :encode_edit
  get 'account/encodes/:id/destroy', to: 'encodes#delete_encode', as: :delete_encode

  resources :latars
  get 'account/latars/new', to: 'latars#new', as: :latar_new
  get 'account/latars/:id/edit', to: 'latars#edit', as: :latar_edit
  get 'account/latars/:id/destroy', to: 'latars#delete_latar', as: :delete_latar

  resources :vidsubs
  get 'account/vidsubs/new', to: 'vidsubs#new', as: :vidsub_new
  get 'account/vidsubs/:id/edit', to: 'vidsubs#edit', as: :vidsub_edit
  get 'account/vidsubs/:id/destroy', to: 'vidsubs#delete_vidsub', as: :delete_vidsub

  resources :framerates
  get 'account/framerates/new', to: 'framerates#new', as: :framerate_new
  get 'account/framerates/:id/edit', to: 'framerates#edit', as: :framerate_edit
  get 'account/framerates/:id/destroy', to: 'framerates#delete_framerate', as: :delete_framerate

  resources :aeplugins
  get 'account/aeplugins/new', to: 'aeplugins#new', as: :aeplugin_new
  get 'account/aeplugins/:id/edit', to: 'aeplugins#edit', as: :aeplugin_edit
  get 'account/aeplugins/:id/destroy', to: 'aeplugins#delete_aeplugin', as: :delete_aeplugin

  resources :languages
  get 'account/languages/new', to: 'languages#new', as: :language_new

app/controllers/home_controller.rb
class HomeController < ApplicationController

	layout "home"

	def index
		
	end
end

app/views/home/_code.html.erb
<svg version="1.1" id="code" class="intan" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve">
	<g id="XMLID_2_">
		<path id="XMLID_5_" class="st0" d="M27.9,15.6l-7.1-6c-0.2-0.2-0.5-0.1-0.7,0.1c-0.2,0.2-0.1,0.5,0.1,0.7l6.6,5.6l-6.6,5.5
		c-0.2,0.2-0.2,0.5-0.1,0.7c0.1,0.1,0.2,0.2,0.4,0.2c0.1,0,0.2,0,0.3-0.1l7.1-5.9C28,16.3,28,16.2,28,16C28,15.9,28,15.7,27.9,15.6z
		"/>
		<path id="XMLID_4_" class="st0" d="M11.9,9.7c-0.2-0.2-0.5-0.2-0.7-0.1l-7.1,6C4,15.7,4,15.9,4,16c0,0.1,0.1,0.3,0.2,0.4l7.1,5.9
		c0.1,0.1,0.2,0.1,0.3,0.1c0.1,0,0.3-0.1,0.4-0.2c0.2-0.2,0.1-0.5-0.1-0.7L5.2,16l6.6-5.6C12.1,10.3,12.1,10,11.9,9.7z"/>
		<path id="XMLID_3_" class="st0" d="M17.6,9.6C17.3,9.5,17,9.7,17,9.9L14,21.8c-0.1,0.3,0.1,0.5,0.4,0.6c0,0,0.1,0,0.1,0
		c0.2,0,0.4-0.2,0.5-0.4l2.9-11.9C18,9.9,17.8,9.7,17.6,9.6z"/>
	</g>
</svg>

app/views/home/_graphic.html.erb
<svg version="1.1" id="graph" class="intan" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve">
<path class="st0" d="M25,11.3L20.7,7c-0.1-0.1-0.2-0.1-0.4-0.1l0,0c-0.1,0-0.3,0.1-0.4,0.1L8.1,18.9C8,18.9,8,19,8,19.1l-1.1,5.4
c0,0.2,0,0.3,0.1,0.5c0.1,0.1,0.2,0.1,0.4,0.1c0,0,0.1,0,0.1,0l5.4-1.1c0.1,0,0.2-0.1,0.3-0.1L25,12C25.2,11.8,25.2,11.5,25,11.3z
M12.8,22.8l-3.6-3.6l9.5-9.5l3.6,3.6L12.8,22.8z M8.8,20.2l3,3L8,24L8.8,20.2z M23,12.6L19.4,9l0.9-0.9l3.6,3.6L23,12.6z"/>
</svg>

app/views/home/index.html.erb
<%= title "Themes, 3D Model, Fonts, and More ~ KAPHOO" %>
<div class="header">
	<div class="navbar navbar-default this-nav">
		<div class="container contain-cus">
			<div class="navbar-header">
				<a href="#" class="navbar-brand"><%= image_tag ("logo/logo.png"), class: "logo" %></a>
			</div>
			<ul class="nav navbar-nav navbar-right mnu">
				<li><a href="#">HOME</a></li>
				<li><a href="#">PRODUCTS</a></li>
				<li><a href="#">FEATURES</a></li>
				<li><a href="#">BLOG</a></li>
				<li><a href="#">ABOUT</a></li>
				<li><%= link_to "LOGIN", sign_in_path %></li>
			</ul>
		</div>
	</div>
	<div class="capt">
		<div class="container contain-cus">
			<h2>BUILD, GROW YOUR CREATIVITY &amp; WE</h2>
			<h4>HELP YOU PROMOTING YOUR PRODUCTS</h4>
			<%= link_to "GET STARTED", sign_up_path, class: "btn-start" %>
			<div class="img_brw">
				<%= image_tag("web_front.png", class: "img_1" )%>
			</div>
		</div>
	</div>
</div>
<div class="features">
	<div class="container contain-cus">
		<div class="title">
			<h3>SIXART FEATURES</h3>
			<p>Get the a variety of products of quality and professional sellers</p>
			<div class="line">
				<hr>
			</div>
		</div>
		<div class="lst_1">
			<div class="col-md-4">
				<div class="icons_i">
					<%= image_tag ("icon/_1.png") %>
					<h4>
						Free Products / Week
					</h4>
					<p>
						Every week we will be on sale in the form of free products with good quality
					</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="icons_i">
					<%= image_tag ("icon/_2.png") %>
					<h4>
						Social Media Marketing
					</h4>
					<p>
						To ease the process of marketing the
						product. we provide facilities for
						social media marketing.
					</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="icons_i">
					<%= image_tag ("icon/_3.png") %>
					<h4>
						Easy Transactions
					</h4>
					<p>
						For the payment of any purchase of products
						in our store. You will be given the ease
						in the payment process
					</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="icons_i">
					<%= image_tag("icon/_4.png") %>
					<h4>
						Quality Products
					</h4>
					<p>
						We offer a wide range of products that have
						a very good quality and are made 
						by a professional.
					</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="icons_i">
					<%= image_tag("icon/_5.png") %>
					<h4>
						Post &amp; Find Jobs
					</h4>
					<p>
						We provide a place for you if you want to
						hire employees who are professional
						and experienced
					</p>
				</div>
			</div>
			<div class="col-md-4">
				<div class="icons_i">
					<%= image_tag("icon/_6.png") %>
					<h4>
						Wishlist Products
					</h4>
					<p>
						This feature will make it easy for you
						to compare products that have
						the same quality.
					</p>
				</div>
			</div>
		</div>
		<div class="clear"></div>
	</div>
</div>
<div class="products" id="item_pro">
	<div class="container contain-cus">
		<div class="title">
			<h3>What We Provide to You?</h3>
			<p>We Offer a Variety of Products and Services for You</p>
			<div class="line">
				<hr>
			</div>
		</div>
		<div class="pro-main">
			<div class="top_oe grd" id="io">
				<%= link_to themes_path do %>
					<div class="col-md-3 _this_col col_top_1 vangkes1">
						<%= link_to themes_path do %>
							<object data="" type="">
								<%= render 'home/theme' %>
							</object>
							<h4 class="th_">ThemeArts</h4>
						<% end %>
					</div>
				<% end %>
				<div class="ver">
					<span class="sparator"></span>
				</div>
				<a href="#">
					<div class="col-md-3 _this_col col_top_2 vangkes2">
						<a href="#">
							<object data="" type="">
								<%= render 'home/code' %>
								<h4 class="cd_">CodeArts</h4>
							</object>
						</a>
					</div>
				</a>
				<div class="ver">
					<span class="sparator"></span>
				</div>
				<a href="#">
					<div class="col-md-3 _this_col col_top_3 vangkes3">
						<a href="#">
							<object data="" type="">
								<%= render 'home/graphic' %>
							</object>
							<h4 class="grp_">Graphiku</h4>
						</a>
					</div>
				</a>
				<div class="ver">
					<span class="sparator"></span>
				</div>
				<a href="#">
					<div class="col-md-3 _this_col col_top_4 vangkes4">
						<a href="#">
							<object data="" type="">
								<%= render 'home/threed' %>
							</object>
							<h4 class="drm_">3Dream</h4>
						</a>
					</div>
				</a>
				<div class="clear"></div>
			</div>
			<div class="hor">
				<!-- <hr> -->
			</div>
			<div class="bottom_oe grd" id="oi">
				<div class="col-md-3 _this_col col_top_1 vangkes5">
					<a href="#">
						<object data="" type="">
							<%= render 'home/video' %>
						</object>
						<h4 class="vdo_">VideoArts</h4>
					</a>
				</div>
				<span class="sparator"></span>
				<div class="col-md-3 _this_col col_top_2 vangkes6">
					<a href="#">
						<object data="" type="">
							<%= render 'home/photo' %>
						</object>
						<h4 class="pto_">Photostock</h4>
					</a>
				</div>
				<span class="sparator"></span>
				<div class="col-md-3 _this_col col_top_3 vangkes7">
					<a href="#">
						<object data="" type="">
							<%= render 'home/font' %>
						</object>
						<h4 class="fot_">Fonts</h4>
					</a>
				</div>
				<span class="sparator"></span>
				<div class="col-md-3 _this_col vangkes8">
					<a href="#">
						<object data="" type="">
							<%= render 'home/course' %>
						</object>
						<h4 class="crs_">Course</h4>
					</a>
				</div>
				<div class="clear"></div>
			</div>
		</div>
	</div>
</div>
<div class="team">
	<div class="container contain-cus">
		<div class="title">
			<h3>how we work?</h3>
			<div class="line">
				<hr>
			</div>
			<div class="kui">
				<p>
					Pixarts is proudly based in Yogyakarta, Indonesia, but our people and community live and work from all over the world.
					<br><br>
					We believe good ideas deserve a chance to grow. We believe people deserve to earn a living doing what they love. We believe in making it easy to get things done.
				</p>
			</div>
			<div class="awk">
				<a href="#" class="bds">KNOW MORE</a>
			</div>
		</div>
	</div>
</div>
<div class="community">
	<div class="container-contain-cus">
		<div class="title">
			<h3>our community</h3>
			<div class="line">
				<hr>
			</div>
		</div>
		<div class="cout">
			<p>
				Pixarts is a platform for handcrafted, mousemade design content from independent creatives around the world. We're passionate about making beautiful design simple and accessible to everyone.
			</p>
			<div class="gdf">
				<a href="#" class="bht">SIGN UP</a>
			</div>
		</div>
	</div>
</div>
<div class="blog">
	<div class="container contain-cus">
		<div class="title">
			<h3>improve your skill</h3>
			<div class="kl">
				<p>We provide a free tutorial to improve your skills &amp; knowledge</p>
			</div>
			<div class="line">
				<hr>
			</div>
		</div>
		<div class="lst-blg">
			<div class="col-md-4 ski">
				<a href="#">
					<%= image_tag("blog/1.png") %>
					<div class="xnb">
						<p>Be Good Designer...</p>
						<div class="col-md-6 vdf">
							<span>By Fooo</span>
						</div>
						<div class="col-md-6 vdf">
							<span>Like</span>
						</div>
					</div>
				</a>
			</div>
			<div class="col-md-4 ski">
				<a href="#">
					<%= image_tag("blog/2.png") %>
					<div class="xnb">
						<p>Be Good Designer...</p>
						<div class="col-md-6 vdf">
							<span>By Fooo</span>
						</div>
						<div class="col-md-6 vdf">
							<span>Like</span>
						</div>
					</div>
				</a>
			</div>
			<div class="col-md-4 ski">
				<a href="#">
					<%= image_tag("blog/3.png") %>
					<div class="xnb">
						<p>Be Good Designer...</p>
						<div class="col-md-6 vdf">
							<span>By Fooo</span>
						</div>
						<div class="col-md-6 vdf">
							<span>Like</span>
						</div>
					</div>
				</a>
			</div>
			<div class="clear"></div>
			<div class="bgdf">
				<a href="#" class="njg">KNOW MORE</a>
			</div>
		</div>
	</div>
</div>
<div class="footer">
	<div class="container-fluid">
		<ul class="list-inline pull-left vft">
			<li><a href="#">Free Goods</a></li>
			<li><a href="#">Community</a></li>
			<li><a href="#">Jobs</a></li>
			<li><a href="#">Blog</a></li>
			<li><a href="#">Forums</a></li>
			<li><a href="#">Help</a></li>
		</ul>
		<ul class="list-inline pull-right xtx">
			<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
			<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
			<li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
			<li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>
			<li><a href="#"><i class="fa fa-github-alt" aria-hidden="true"></i></a></li>
			<li><a href="#"><i class="fa fa-dribbble" aria-hidden="true"></i></a></li>
			<li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i></a></li>
		</ul>
	</div>
</div>