config/routes.rb
  get 'account/browsers/new', to: 'browsers#new', as: :browser_new
  get 'account/browsers/:id/edit', to: 'browsers#edit', as: :browser_edit
  get 'account/browsers/:id/destroy', to: 'browsers#delete_browser', as: :delete_browser

  resources :dependencies
  get 'account/dependencies/new', to: 'dependencies#new', as: :dependency_new
  get 'account/dependencies/:id/edit', to: 'dependencies#edit', as: :dependency_edit
  get 'account/dependencies/:id/destroy', to: 'dependencies#delete_dependency', as: :delete_dependency

  resources :compatibles
  get 'account/compatibles/new', to: 'compatibles#new', as: :compatible_new
  get 'account/compatibles/:id/edit', to: 'compatibles#edit', as: :compatible_edit
  get 'account/compatibles/:id/destroy', to: 'compatibles#delete_compatible', as: :delete_compatible

  resources :includes
  get 'account/includes/new', to: 'includes#new', as: :include_new
  get 'account/includes/:id/edit', to: 'includes#edit', as: :include_edit
  get 'account/includes/:id/destroy', to: 'includes#delete_include', as: :delete_include

  resources :codesubs
  get 'account/codesubs/new', to: 'codesubs#new', as: :codesub_new
  get 'account/codesubs/:id/edit', to: 'codesubs#edit', as: :codesub_edit
  get 'account/codesubs/:id/destroy', to: 'codesubs#delete_codesub', as: :delete_codesub

  resources :softopens
  get 'account/softopens/new', to: 'softopens#new', as: :softopen_new
  get 'account/softopens/:id/edit', to: 'softopens#edit', as: :softopen_edit
  get 'account/softopens/:id/destroy', to: 'softopens#delete_softopen', as: :delete_softopen

  resources :industries
  get 'account/industries/new', to: 'industries#new', as: :industry_new
  get 'account/industries/:id/edit', to: 'industries#edit', as: :industry_edit
  get 'account/industries/:id/destroy', to: 'industries#delete_industry', as: :delete_industry

  resources :softopen3ds
  get 'account/softopen3ds/new', to: 'softopen3ds#new', as: :softopen3d_new
  get 'account/softopen3ds/:id/edit', to: 'softopen3ds#edit', as: :softopen3d_edit
  get 'account/softopen3ds/:id/destroy', to: 'softopen3ds#delete_softopen3d', as: :delete_softopen3d

  resources :modelsubs
  get 'account/modelsubs/new', to: 'modelsubs#new', as: :modelsub_new
  get 'account/modelsubs/:id/edit', to: 'modelsubs#edit', as: :modelsub_edit
  get 'account/modelsubs/:id/destroy', to: 'modelsubs#delete_modelsub', as: :delete_modelsub

  resources :genres
  get 'account/genres/new', to: 'genres#new', as: :genre_new
  get 'account/genres/:id/edit', to: 'genres#edit', as: :genre_edit
  get 'account/genres/:id/destroy', to: 'genres#delete_genre', as: :delete_genre

   resources :encodes
  get 'account/encodes/new', to: 'encodes#new', as: :encode_new
  get 'account/encodes/:id/edit', to: 'encodes#edit', as: :encode_edit
  get 'account/encodes/:id/destroy', to: 'encodes#delete_encode', as: :delete_encode

  resources :latars
  get 'account/latars/new', to: 'latars#new', as: :latar_new
  get 'account/latars/:id/edit', to: 'latars#edit', as: :latar_edit
  get 'account/latars/:id/destroy', to: 'latars#delete_latar', as: :delete_latar

  resources :vidsubs
  get 'account/vidsubs/new', to: 'vidsubs#new', as: :vidsub_new
  get 'account/vidsubs/:id/edit', to: 'vidsubs#edit', as: :vidsub_edit
  get 'account/vidsubs/:id/destroy', to: 'vidsubs#delete_vidsub', as: :delete_vidsub

  resources :framerates
  get 'account/framerates/new', to: 'framerates#new', as: :framerate_new
  get 'account/framerates/:id/edit', to: 'framerates#edit', as: :framerate_edit
  get 'account/framerates/:id/destroy', to: 'framerates#delete_framerate', as: :delete_framerate

  resources :aeplugins
  get 'account/aeplugins/new', to: 'aeplugins#new', as: :aeplugin_new
  get 'account/aeplugins/:id/edit', to: 'aeplugins#edit', as: :aeplugin_edit
  get 'account/aeplugins/:id/destroy', to: 'aeplugins#delete_aeplugin', as: :delete_aeplugin

  resources :languages
  get 'account/languages/new', to: 'languages#new', as: :language_new
  get 'account/languages/:id/edit', to: 'languages#edit', as: :language_edit
  get 'account/languages/:id/destroy', to: 'languages#delete_language', as: :delete_language

  resources :conversations do 
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :notes
  get 'account/notes', to: 'accounts#note', as: :note_account
  get 'account/notes/:id/racoon', to: 'accounts#note_edit', as: :note_edit
  get 'account/destroy/:id', to: 'notes#a_destroy'
  get 'account/b_destroy/:note_id/:id', to: 'notes#b_destroy'
  get 'account/shared/:id', to: 'notes#shared'

  resources :vacancies
  resources :teams
  get 'account/teams/data/new', to: 'teams#new', as: :team_account
  get 'account/teams/data/:id', to: 'teams#edit', as: :team_edit
  get 'account/teams/:id/destroy', to: 'teams#delete_team'
  get 'account/teams/data/:id/members', to: 'teams#show', as: :show_team
  get 'account/products/all_themes/:themes', to: 'accounts#all_product', as: :all_themes
  get 'account/products/delete/:id', to: 'themes#delete_by_admin'
  get 'account/products/all_codes/:codes', to: 'accounts#all_product', as: :all_codes
  get 'account/products/delete_code/:id', to: 'codes#delete_by_admin'
  get 'account/products/all_graphics/:graphics', to: 'accounts#all_product', as: :all_graphics
  get 'account/products/delete_graphic/:id', to: 'graphics#delete_by_admin'
  get 'account/products/all_t3ds/:t3ds', to: 'accounts#all_product', as: :all_t3ds
  get 'account/products/delete_t3d/:id', to: 't3ds#delete_by_admin'
  get 'account/products/all_videofxes/:videofxes', to: 'accounts#all_product', as: :all_videofxes
  get 'account/products/delete_videofx/:id', to: 'videofxes#delete_by_admin'
  get 'account/products/all_fonts/:fonts', to: 'accounts#all_product', as: :all_fonts
  get 'account/products/delete_font/:id', to: 'fonts#delete_by_admin'
  get 'account/products/all_courses/:courses', to: 'accounts#all_product', as: :all_courses
  get 'account/products/delete_course/:id', to: 'courses#delete_by_admin'

  get 'account/transaction/order/completed', to: 'accounts#order', as: :data_order
  get 'account/transaction/data_1/:week/order/completed', to: 'accounts#order', as: :data_order_week
  get 'account/transaction/data_2/:day/order/completed', to: 'accounts#order', as: :data_order_day
  get 'account/transaction/data_3/:month/order/completed', to: 'accounts#order', as: :data_order_month

  get 'account/vacancies/data_1/:programmer', to: 'accounts#all_vacancy', as: :all_vacancy_programmer
  get 'account/vacancies/data_2/:designer', to: 'accounts#all_vacancy', as: :all_vacancy_designer
  get 'account/vacancies/data_3/:animator', to: 'accounts#all_vacancy', as: :all_vacancy_animator
  get 'account/vacancies/data_4/:network', to: 'accounts#all_vacancy', as: :all_vacancy_network
  get 'account/items', to: 'accounts#free_item', as: :free_item
  get 'account/items/:id', to: 'accounts#free_destroy', as: :destroy_free
  get 'vacancies/data/search', to: 'vacancies#search_vacancy', as: :vacancies_search
  
  #freeitem

  get 'themes/freeitem/:id', to: 'themes#free_theme'
  get 'codes/freeitem/:id', to: 'codes#free_code'
  get 'graphics/freeitem/:id', to: 'graphics#free_graphic'
  get 't3ds/freeitem/:id', to: 't3ds#free_t3d'
  get 'videofxes/freeitem/:id', to: 'videofxes#free_videofx'
  get 'fonts/freeitem/:id', to: 'fonts#free_font'
  get 'courses/freeitem/:id', to: 'courses#free_course'

  get 'delete/carts/:id', to: 'line_items#delete', as: :line_items_delete
  
  get 'themes/:id/upload', to: 'themes#upload', as: :upload
  get 'codes/:id/upload', to: 'codes#upload', as: :upload_code
  get 'graphics/:id/upload', to: 'graphics#upload', as: :upload_graphic
  get 't3dreams/:id/upload', to: 't3ds#upload', as: :upload_t3d
  get 'videofxes/:id/upload', to: 'videofxes#upload', as: :upload_videofx
  get 'fonts/upload', to: 'fonts#new'
  get 'courses/:id/upload', to: 'courses#upload', as: :upload_course
  get 'courses/:id/curriculum', to: 'courses#manage_course', as: :manage_course

  get 'themes/item/:id', to: 'themes#item', as: :item
  get 'codes/item/:id', to: 'codes#item', as: :item_code
  get 'graphics/item/:id', to: 'graphics#item', as: :item_graphic
  get 't3dreams/item/:id', to: 't3ds#item', as: :item_t3d
  get 'videofxes/item/:id', to: 'videofxes#item', as: :item_videofx
  get 'fonts/item/:id', to: 'fonts#item', as: :item_font
  get 'courses/item/:id', to: 'courses#item', as: :item_course

  get 'themes/item/:id/screenshot', to: 'themes#screenshot', :as => :screenshot
  get 'codes/item/:id/screenshot', to: 'codes#screenshot', :as => :screenshot_code
  get 'graphics/item/:id/screenshot', to: 'graphics#screenshot', :as => :screenshot_graphic
  get 't3dreams/item/:id/screenshot', to: 't3ds#screenshot', :as => :screenshot_t3d
  get 'videofxes/item/:id/screenshot', to: 'videofxes#screenshot', :as => :screenshot_videofx
  get 'fonts/item/:id/screenshot', to: 'fonts#screenshot', :as => :screenshot_font

  get 'themes/aprroved/:id/theme', to: 'themes#success_reviewer', as: :success_reviewer
  get 'codes/aprroved/:id/code', to: 'codes#success_reviewer', as: :cdsuccess_reviewer
  get 't3dreams/aprroved/:id/t3dream', to: 't3ds#success_reviewer', as: :t3success_reviewer
  get 'videofxes/aprroved/:id/videofx', to: 'videofxes#success_reviewer', as: :vsuccess_reviewer
  get 'fonts/aprroved/:id/font', to: 'fonts#success_reviewer', as: :fsuccess_reviewer
  get 'courses/aprroved/:id/course', to: 'courses#success_reviewer', as: :cvsuccess_reviewer
  get 'graphics/aprroved/:id/graphic', to: 'graphics#success_reviewer', as: :gsuccess_reviewer

  get 'themes/reject/:id/theme', to: 'themes#reject_reviewer', as: :treject_reviewer
  get 'codes/reject/:id/code', to: 'codes#reject_reviewer', as: :creject_reviewer
  get 't3dreams/reject/:id/t3dream', to: 't3ds#reject_reviewer', as: :t3reject_reviewer
  get 'videofxes/reject/:id/videofx', to: 'videofxes#reject_reviewer', as: :vreject_reviewer

app/models/framerate.rb
class Framerate < ApplicationRecord
	has_many :videorates
	has_many :videofxes, through: :videorates
end

app/controllers/framerates_controller.rb
class FrameratesController < ApplicationController
  
  before_action :only_admin
  before_action :set_framerate, only: [:edit, :update, :delete_framerate]
  layout "account"

  def new
    @framerate = Framerate.new
    @framerates = Framerate.all.order('created_at desc')
  end

  def create
    @framerate = Framerate.new(params_framerate)
    if @framerate.save
      redirect_to framerate_new_url
    end
  end

  def edit
    @framerates = Framerate.all.order('created_at desc')
  end

  def update
    if @framerate.update(params_framerate)
      redirect_to framerate_new_url
    end
  end

  def delete_framerate
    @framerate.destroy
  end

  private

  def params_framerate
    params.require(:framerate).permit(:name)
  end

  def only_admin
    redirect_to dashboard_url if !current_user.admin?
  end

  def set_framerate
    @framerate = Framerate.find(params[:id])
  end

end

app/views/framerates/_form.html.erb
<%= form_for @framerate do |f| %>
  <div class="col-md-8 brek brrroo">
    <div class="user_chooses">
      <div class="kate_kat">
        <h2>Add New Framerate</h2>
        <p>configuration your store to convince buyers with the quality of your products</p>
      </div>
      <div class="sod data-acct">
        <div class="form-group fk">
          <span class="fl">Framerate Name</span>
          <div class="fs">
            <%= f.text_field :name, class: "form-control sami", require: true %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4 brok prek">
    <div class="mnu_fuk">
      <div class="btn-pi">
        <%= f.submit "SUBMIT", class: "btn_update" %>
      </div>
    </div>
  </div>
<% end %>

app/views/framerates/_framerate.html.erb
<% index = framerate_counter + 1 %>
<%= content_tag "div", id: "framerate3265", data: {framerate: framerate.to_json(only: [:slug])} do %>
  <li id="daddyyoio51_<%= framerate.id %>" class="_idih <%= 'tran' if (index + 1)%2 == 0 %>">
    <ul class="list-inline keke">
      <li class="_id cfdl">
        <%= index %>
      </li>
      <li class="_name cfdl">
        <%= framerate.name %>
      </li>
      <li class="_unit cfdl">
        <ul class="list-inline siut">
          <li><%= link_to framerate_edit_url(framerate.id) do %><span class="lnr lnr-magic-wand"><% end %></li>
          <li><a onclick="dellFramerate(<%= framerate.id %>)" id="data_<%#= category.slug %>"><span class="lnr lnr-trash"></span></a></li>
        </ul>
      </li>
    </ul>
  </li>
<% end %>

app/views/framerates/edit.html.erb
<%= title "Edit Framerate ~ KHAPOO" %>
<div class="setting">
  <%= render "framerates/form" %>
  <div class="col-md-8 brek brrroo">
    <div class="all_cta">
      <div class="isi-menu-mail">
        <div class="earn_titlr befh">
          <ul class="list-inline yoon">
            <li class="id_">ID</li>
            <li class="name_">FRAMERATE NAME</li>
            <li class="unit_">ACTION</li>
          </ul>
        </div>
        <div class="content_earn">
          <ul class="tqx" id="onyou">
           <%= render @framerates %> 
          </ul>
        </div>
      </div>    
    </div>
  </div>
</div>
<script>
$('.aktif').removeClass();
$('.sup_ot').addClass('aktif');
</script>

app/views/framerates/new.html.erb
<%= title "Add Framerate ~ KHAPOO" %>
<div class="setting">
  <%= render "framerates/form" %>
  <div class="col-md-8 brek brrroo">
    <div class="all_cta">
      <div class="isi-menu-mail">
        <div class="earn_titlr befh">
          <ul class="list-inline yoon">
            <li class="id_">ID</li>
            <li class="name_">FRAMERATE NAME</li>
            <li class="unit_">ACTION</li>
          </ul>
        </div>
        <div class="content_earn">
          <ul class="tqx" id="onyou">
           <%= render @framerates %> 
          </ul>
        </div>
      </div>    
    </div>
  </div>
</div>
<script>
$('.aktif').removeClass();
$('.sup_ot').addClass('aktif');
</script>