config/routes.rb
Rails.application.routes.draw do
  post 'user/store/:id/follow_user', to: 'relationships#follow_user', as: :follow_user

  post 'user/store/:id/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'user/delete/:id', to: 'users#delete_user'

  get 'password_resets/new'

  get 'password_resets/edit'

  mount ActionCable.server => '/cable'

  resources :home, only: [:index]
  #themes routes
  resources :themes do
    resources :comments
    resources :reviews, only: [:create]
    member do
      get 'screenshot/:screenshot_id/delete', to: 'themes#delete_screenshot', as: :delete_screenshot
      get 'broke/:broke_id/delete', to: 'themes#delete_broke', as: :delete_broke
      get :theme_suka, to: 'themes#theme_suka'
      get :theme_unsuka, to: 'themes#theme_unsuka'
      get :delete_theme, to: 'themes#delete_theme'
      put :like, to: 'themes#upvote'
      put :dislike, to: 'themes#downvote'
    end
  end

  get 'themes/this/:recent', to: 'themes#index', as: :themes_recent
  get 'themes/that/:recoms', to: 'themes#index', as: :themes_recoms

  resources :codes do
    resources :comments
    resources :reviews, only: [:create]
    member do 
      get 'screenshot/:screenshot_id/delete', to: 'codes#delete_screenshot', as: :delete_cdscreenshot
      get 'broke/:broke_id/delete', to: 'codes#delete_broke', as: :delete_cdbroke
      get :delete_code, to: 'codes#delete_code'
      get :code_suka, to: 'codes#code_suka'
      get :code_unsuka, to: 'codes#code_unsuka'
      put :like, to: 'codes#upvote'
      put :dislike, to: 'codes#downvote'
    end
  end

  get 'codes/this/:recent', to: 'codes#index', as: :codes_recent
  get 'codes/that/:recoms', to: 'codes#index', as: :codes_recoms

  resources :graphics do
    resources :comments
    resources :reviews, only: [:create]
    member do 
      get 'screenshot/:screenshot_id/delete', to: 'graphics#delete_screenshot', as: :delete_ghscreenshot
      get 'broke/:broke_id/delete', to: 'graphics#delete_broke', as: :delete_ghbroke
      get 'delete_graphic', to: 'graphics#delete_graphic'
      get :graphic_suka, to: 'graphics#graphic_suka'
      get :graphic_unsuka, to: 'graphics#graphic_unsuka'
      put :like, to: 'graphics#upvote'
      put :dislike, to: 'graphics#downvote'
    end
  end

  get 'graphics/this/:recent', to: 'graphics#index', as: :graphics_recent
  get 'graphics/that/:recoms', to: 'graphics#index', as: :graphics_recoms

  resources :t3ds do
    resources :comments
    resources :reviews, only: [:create]
    member do
      get 'screenshot/:screenshot_id/delete', to: 't3ds#delete_screenshot', as: :delete_t3screenshot
      get 'broke/:broke_id/delete', to: 't3ds#delete_broke', as: :delete_t3broke
      get :delete_t3d, to: 't3ds#delete_t3d'
      get :t3d_suka, to: 't3ds#t3d_suka'
      get :t3d_unsuka, to: 't3ds#t3d_unsuka'
      put :like, to: 't3ds#upvote'
      put :dislike, to: 't3ds#downvote'
    end
  end

  get 't3dreams/this/:recent', to: 't3ds#index', as: :t3ds_recent
  get 't3ds/that/:recoms', to: 't3ds#index', as: :t3ds_recoms

  resources :videofxes do
    resources :comments
    resources :reviews, only: [:create]
    member do 
      get 'videm/:videm_id/delete', to: 'videofxes#delete_videm', as: :delete_videm
      get 'broke/:broke_id/delete', to: 'videofxes#delete_broke', as: :delete_vbroke
      get :delete_videofx, to: 'videofxes#delete_videofx'
      get :video_suka, to: 'videofxes#video_suka'
      get :video_unsuka, to: 'videofxes#video_unsuka'
      put :like, to: 'videofxes#upvote'
      put :dislike, to: 'videofxes#downvote'
    end
  end
  get 't3dreams', to: 't3ds#index'
  get 't3dreams/new', to: 't3ds#new'
  get 'videofxes/this/:recent', to: 'videofxes#index', as: :videofxes_recent
  get 'videofxes/that/:recoms', to: 'videofxes#index', as: :videofxes_recoms

  resources :fonts do
    resources :comments
    resources :reviews, only: [:create]
    member do
      get 'screenshot/:screenshot_id/delete', to: 'fonts#delete_screenshot', as: :delete_ftscreenshot
      get 'broke/:broke_id/delete', to: 'fonts#delete_broke', as: :delete_ftbroke
      get :delete_font, to: 'fonts#delete_font'
      get :font_suka, to: 'fonts#font_suka'
      get :font_unsuka, to: 'fonts#font_unsuka'
      put :like, to: 'fonts#upvote'
      put :dislike, to: 'fonts#downvote'
    end
  end

  get 'fonts/this/:recent', to: 'fonts#index', as: :fonts_recent
  get 'fonts/that/:recoms', to: 'fonts#index', as: :fonts_recoms
  

   resources :courses do
    resources :comments
    resources :reviews, only: [:create]
    resources :headsecs do
      resources :lectures
    end
    member do
      get 'freepi/:freepi_id/delete', to: 'courses#delete_trailer', as: :delete_trailer
      get 'cofile/:cofile_id/delete', to: 'courses#delete_cofile', as: :delete_cofile
      get :delete_course, to: 'courses#delete_course'
      get :course_suka, to: 'courses#course_suka'
      get :course_unsuka, to: 'courses#course_unsuka'
      put :like, to: 'courses#upvote'
      put :dislike, to: 'courses#downvote'
    end
  end

  get 'courses/this/:recent', to: 'courses#index', as: :courses_recent
  get 'courses/that/:recoms', to: 'courses#index', as: :courses_recoms
  resources :akusukas, only: [:new, :create]
  resources :teams do
    resources :messagereviewers
  end

  resources :carts
  resources :line_items
  resources :payment_noties
  resources :categories
  get 'account/categories/new', to: 'categories#new', as: :category_new
  get 'account/categories/:id/edit', to: 'categories#edit', as: :category_edit
  get 'account/categories/:id/destroy', to: 'categories#delete_category', as: :delete_category

  resources :subcategories
  get 'account/subcategories/new', to: 'subcategories#new', as: :subcategory_new
  get 'account/subcategories/:id/edit', to: 'subcategories#edit', as: :subcategory_edit
  get 'account/subcategories/:id/destroy', to: 'subcategories#delete_subcategory', as: :delete_subcategory
  
  resources :browsers
  get 'account/browsers/new', to: 'browsers#new', as: :browser_new
  get 'account/browsers/:id/edit', to: 'browsers#edit', as: :browser_edit
  get 'account/browsers/:id/destroy', to: 'browsers#delete_browser', as: :delete_browser

  resources :dependencies
  get 'account/dependencies/new', to: 'dependencies#new', as: :dependency_new
  get 'account/dependencies/:id/edit', to: 'dependencies#edit', as: :dependency_edit
  get 'account/dependencies/:id/destroy', to: 'dependencies#delete_dependency', as: :delete_dependency

  resources :compatibles
  get 'account/compatibles/new', to: 'compatibles#new', as: :compatible_new
  get 'account/compatibles/:id/edit', to: 'compatibles#edit', as: :compatible_edit
  get 'account/compatibles/:id/destroy', to: 'compatibles#delete_compatible', as: :delete_compatible

  resources :includes
  get 'account/includes/new', to: 'includes#new', as: :include_new
  get 'account/includes/:id/edit', to: 'includes#edit', as: :include_edit
  get 'account/includes/:id/destroy', to: 'includes#delete_include', as: :delete_include

  resources :codesubs
  get 'account/codesubs/new', to: 'codesubs#new', as: :codesub_new
  get 'account/codesubs/:id/edit', to: 'codesubs#edit', as: :codesub_edit
  get 'account/codesubs/:id/destroy', to: 'codesubs#delete_codesub', as: :delete_codesub

  resources :softopens
  get 'account/softopens/new', to: 'softopens#new', as: :softopen_new
  get 'account/softopens/:id/edit', to: 'softopens#edit', as: :softopen_edit
  get 'account/softopens/:id/destroy', to: 'softopens#delete_softopen', as: :delete_softopen

  resources :industries
  get 'account/industries/new', to: 'industries#new', as: :industry_new
  get 'account/industries/:id/edit', to: 'industries#edit', as: :industry_edit
  get 'account/industries/:id/destroy', to: 'industries#delete_industry', as: :delete_industry

  resources :softopen3ds
  get 'account/softopen3ds/new', to: 'softopen3ds#new', as: :softopen3d_new
  get 'account/softopen3ds/:id/edit', to: 'softopen3ds#edit', as: :softopen3d_edit
  get 'account/softopen3ds/:id/destroy', to: 'softopen3ds#delete_softopen3d', as: :delete_softopen3d

  resources :modelsubs
  get 'account/modelsubs/new', to: 'modelsubs#new', as: :modelsub_new
  get 'account/modelsubs/:id/edit', to: 'modelsubs#edit', as: :modelsub_edit
  get 'account/modelsubs/:id/destroy', to: 'modelsubs#delete_modelsub', as: :delete_modelsub

  resources :genres
  get 'account/genres/new', to: 'genres#new', as: :genre_new
  get 'account/genres/:id/edit', to: 'genres#edit', as: :genre_edit
  get 'account/genres/:id/destroy', to: 'genres#delete_genre', as: :delete_genre

   resources :encodes
  get 'account/encodes/new', to: 'encodes#new', as: :encode_new
  get 'account/encodes/:id/edit', to: 'encodes#edit', as: :encode_edit
  get 'account/encodes/:id/destroy', to: 'encodes#delete_encode', as: :delete_encode

  resources :latars
  get 'account/latars/new', to: 'latars#new', as: :latar_new
  get 'account/latars/:id/edit', to: 'latars#edit', as: :latar_edit
  get 'account/latars/:id/destroy', to: 'latars#delete_latar', as: :delete_latar

  resources :vidsubs
  get 'account/vidsubs/new', to: 'vidsubs#new', as: :vidsub_new
  get 'account/vidsubs/:id/edit', to: 'vidsubs#edit', as: :vidsub_edit
  get 'account/vidsubs/:id/destroy', to: 'vidsubs#delete_vidsub', as: :delete_vidsub

  resources :framerates
  get 'account/framerates/new', to: 'framerates#new', as: :framerate_new
  get 'account/framerates/:id/edit', to: 'framerates#edit', as: :framerate_edit
  get 'account/framerates/:id/destroy', to: 'framerates#delete_framerate', as: :delete_framerate

  resources :aeplugins
  get 'account/aeplugins/new', to: 'aeplugins#new', as: :aeplugin_new
  get 'account/aeplugins/:id/edit', to: 'aeplugins#edit', as: :aeplugin_edit
  get 'account/aeplugins/:id/destroy', to: 'aeplugins#delete_aeplugin', as: :delete_aeplugin

  resources :languages
  get 'account/languages/new', to: 'languages#new', as: :language_new

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart
  belongs_to :theme
  belongs_to :code
  belongs_to :font
  belongs_to :course
  belongs_to :graphic
  belongs_to :t3d
  belongs_to :videofx
  has_many :notifications, dependent: :destroy

  def full_price
  	unit_price * 1
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    if params[:theme_id]
      @theme = Theme.find(params[:theme_id])
      @line_item = LineItem.create!(:cart => current_cart, :theme => @theme, :unit_price => @theme.price, :license => 'regular', :support => false, :who_have => @theme.user.id)
    elsif params[:code_id]
      @code = Code.find(params[:code_id])
      @line_item = LineItem.create!(:cart => current_cart, :code => @code, :unit_price => @code.price, :license => 'regular', :support => false, :who_have => @code.user.id)
    elsif params[:font_id]
      @font = Font.find(params[:font_id])
      @line_item = LineItem.create!(:cart => current_cart, :font => @font, :unit_price => @font.price, :license => 'regular', :support => false, :who_have => @font.user.id)
    elsif params[:course_id]
      @course = Course.find(params[:course_id])
      @line_item = LineItem.create!(:cart => current_cart, :course => @course, :unit_price => @course.price, :license => 'regular', :support => false, :who_have => @course.user.id)
    elsif params[:graphic_id]
      @graphic = Graphic.find(params[:graphic_id])
      @line_item = LineItem.create!(:cart => current_cart, :graphic => @graphic, :unit_price => @graphic.price, :license => 'regular', :support => false, :who_have => @graphic.user.id)
    elsif params[:t3d_id]
      @t3d = T3d.find(params[:t3d_id])
      @line_item = LineItem.create!(:cart => current_cart, :t3d => @t3d, :unit_price => @t3d.price, :license => 'regular', :support => false, :who_have => @t3d.user.id)
    elsif params[:videofx_id]
      @videofx = Videofx.find(params[:videofx_id])
      @line_item = LineItem.create!(:cart => current_cart, :videofx => @videofx, :unit_price => @videofx.price, :license => 'regular', :support => false, :who_have => @videofx.user.id)
    end
  end

  def edit
    @line_item = LineItem.find(params[:id])
  end

  def update
    @line_item = LineItem.find(params[:id])
    @line_item.update(params[:line_item].permit(:support, :license))
    if @line_item.save
      if @line_item.theme.present?
        if @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.theme.price_ext
        elsif @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.theme.price
        end
        if @line_item.support?
          @line_item.update unit_price: @line_item.unit_price + 30
        elsif !@line_item.support? && @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.theme.price
        elsif !@line_item.support? && @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.theme.price_ext
        end
      elsif @line_item.code.present?
        if @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.code.price_ext
        elsif @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.code.price
        end
        if @line_item.support?
          @line_item.update unit_price: @line_item.unit_price + 30
        elsif !@line_item.support? && @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.code.price
        elsif !@line_item.support? && @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.code.price_ext
        end
      elsif @line_item.font.present?
        if @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.font.price_ext
        elsif @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.font.price
        end
        if @line_item.support?
          @line_item.update unit_price: @line_item.unit_price + 30
        elsif !@line_item.support? && @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.font.price
        elsif !@line_item.support? && @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.font.price_ext
        end
      elsif @line_item.graphic.present?
        if @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.graphic.price_ext
        elsif @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.graphic.price
        end
        if @line_item.support?
          @line_item.update unit_price: @line_item.unit_price + 30
        elsif !@line_item.support? && @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.graphic.price
        elsif !@line_item.support? && @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.graphic.price_ext
        end
      elsif @line_item.t3d.present?
        if @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.t3d.price_ext
        elsif @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.t3d.price
        end
        if @line_item.support?
          @line_item.update unit_price: @line_item.unit_price + 30
        elsif !@line_item.support? && @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.t3d.price
        elsif !@line_item.support? && @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.t3d.price_ext
        end
      elsif @line_item.videofx.present?
        if @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.videofx.price_ext
        elsif @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.videofx.price
        end
        if @line_item.support?
          @line_item.update unit_price: @line_item.unit_price + 30
        elsif !@line_item.support? && @line_item.license == 'regular'
          @line_item.update unit_price: @line_item.videofx.price
        elsif !@line_item.support? && @line_item.license == 'extended'
          @line_item.update unit_price: @line_item.videofx.price_ext
        end
      end
    end
  end

  def delete
    @carts = current_cart.line_items
    @delete = current_cart.line_items.find(params[:id])
    @delete.destroy
  end
end

app/views/line_items/_item.html.erb
<%= @carts.size %>

app/views/line_items/_lineedit.html.erb
<div class="modal-dialog line_cart" role="document">
	<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
				<h4 class="modal-title" id="myModalLabel">Edit Shopping Cart</h4>
			</div>
			<%= form_for @line_item, remote: true do |f| %>
				<div class="modal-body" id="cart_lined">
						<div class="mengh">
							<div class="imgs_u">
								<% if @line_item.theme.present? %> 
									<%= image_tag @line_item.theme.thumbnail_url(:thumbnail), width: '120' %>
								<% elsif @line_item.code.present? %>
									<%= image_tag @line_item.code.thumbnail_url(:thumbnail), width: '120' %>
								<% elsif @line_item.font.present? %>
									<%= image_tag @line_item.font.thumbnail_url(:thumbnail), width: '120' %>
								<% elsif @line_item.course.present? %>
									<%= image_tag @line_item.course.thumbnail_url(:thumbnail), width: '120' %>
								<% elsif @line_item.graphic.present? %>
									<%= image_tag @line_item.graphic.thumbnail_url(:thumbnail), width: '120' %>
								<% elsif @line_item.t3d.present? %>
									<%= image_tag @line_item.t3d.thumbnail_url(:thumbnail), width: '120' %>
								<% elsif @line_item.videofx.present? %>
									<%= image_tag @line_item.videofx.thumbnail_url(:thumbnail), width: '120' %>
								<% end %> 
							</div>
							<div class="kdg68">
								<% if @line_item.theme.present? %> 
									<h2 class="ytr"><%= @line_item.theme.name %></h2>
									<span class="by">by <%= @line_item.theme.user.username %></span>
								<% elsif @line_item.code.present? %>
									<h2 class="ytr"><%= @line_item.code.name %></h2>
									<span class="by">by <%= @line_item.code.user.username %></span>
								<% elsif @line_item.font.present? %>
									<h2 class="ytr"><%= @line_item.font.name %></h2>
									<span class="by">by <%= @line_item.font.user.username %></span>
								<% elsif @line_item.course.present? %>
									<h2 class="ytr"><%= @line_item.course.name %></h2>
									<span class="by">by <%= @line_item.course.user.username %></span>
								<% elsif @line_item.graphic.present? %>
									<h2 class="ytr"><%= @line_item.graphic.name %></h2>
									<span class="by">by <%= @line_item.graphic.user.username %></span>
								<% elsif @line_item.t3d.present? %>
									<h2 class="ytr"><%= @line_item.t3d.name %></h2>
									<span class="by">by <%= @line_item.t3d.user.username %></span>
								<% elsif @line_item.videofx.present? %>
									<h2 class="ytr"><%= @line_item.videofx.name %></h2>
									<span class="by">by <%= @line_item.videofx.user.username %></span>
								<% end %> 
								<h2 class="price"><span>$</span><span id="sguwjj<%= @line_item.id %>"><%= render "line_items/price_modal" %></span></h2>
								<% if @line_item.license == 'extended' %>
									<p class="hfld"><span>License: </span><span id="khgd56dg<%= @line_item.id %>">Extended</span></p>
								<% elsif @line_item.license == 'regular' %> 
									<p class="hfld"><span>License: </span><span id="khgd56<%= @line_item.id %>">Regular</span></p>
								<% end %> 
								<% if @line_item.support? %>
									<p class="hfld sdsd"><span>Support: </span><span id="fhye68<%= @line_item.id %>">Unlimited Support</span></p>
								<% else %>
									<p class="hfld sdsd"><span>Support: </span><span id="basget<%= @line_item.id %>">6 Months Support</span></p>
								<% end %> 
							</div>
						</div>
						<div class="jhdg658">
							<div class="col-md-6 yaaaaa">
								<div class="form-group gjh">
									<%= f.select :license, options_for_select([["Regular", "regular"], ["Extended", "extended"]], @line_item.license), {}, {class: "form-control asal_tahan_aja"} %>
								</div>
							</div>
							<div class="col-md-6 yaaaaa">
								<div class="form-group ooter">
									<%= f.check_box :support, class: "not_sengaja" %>
									<label for="line_item_support"><span class="shgi"></span><span class="shgt">Unlimited Support + $30</span></label>
								</div>
							</div>
						</div>
					</div>
				<div class="modal-footer">
					<%= f.submit "SAVE", class: "btn btn-default",  id: "ref_es" %>
				</div>
			<% end %>
	</div>
</div>

app/views/line_items/_prc.html.erb
<%= item.unit_price.to_i.floor %>

app/views/line_items/_price_modal.html.erb
<%= @line_item.unit_price.to_i.floor %>

app/views/line_items/_total.html.erb
<%= current_cart.total_price.to_i.floor %>

app/views/line_items/create.js.erb
$("#vhgfs").html("<%= escape_javascript(render 'layouts/cart') %>");

app/views/line_items/delete.js.erb
$("#vhgfs").html("<%= escape_javascript(render 'layouts/cart') %>");
$("#kjf83").html("<%= escape_javascript(render 'line_items/item') %>");
$("#sdfg629").html("<%= escape_javascript(render 'line_items/total') %>");

app/views/line_items/edit.js.erb
$("#tengteng3x").html("<%= j (render 'lineedit') %>");
$("#tengteng3x").modal({
	show: 'show',
	backdrop: 'static',
	keyboard: false
});

app/views/line_items/update.js.erb
$("#sguwjj<%= @line_item.id %>").html("<%= escape_javascript(render 'line_items/price_modal') %>");
$("#sdfg629").html("<%= escape_javascript(render 'line_items/total') %>");
$("#djfg68<%= @line_item.id %>").html("<%= escape_javascript render(partial: 'line_items/prc', locals: {item: @line_item}) %>");
<% if @line_item.license == 'extended' %>
	$("#khgd56<%= @line_item.id %>, #khgd56dg<%= @line_item.id %>").html("Extended");
	$("#budgfei<%= @line_item.id %>, #iur983<%= @line_item.id %>").html("<%= escape_javascript link_to "Extended", edit_line_item_url(@line_item.id), remote: true %>");
<% elsif @line_item.license == 'regular' %>
	$("#khgd56dg<%= @line_item.id %>, #khgd56<%= @line_item.id %>").html("Regular");
	$("#budgfei<%= @line_item.id %>, #iur983<%= @line_item.id %>").html("<%= escape_javascript link_to "Regular", edit_line_item_url(@line_item.id), remote: true %>");
<% end %>
<% if @line_item.support? %>
	$("#fhye68<%= @line_item.id %>, #basget<%= @line_item.id %>").html("Unlimited Support");
<% else %>
	$("#fhye68<%= @line_item.id %>, #basget<%= @line_item.id %>").html("6 Months Support");
<% end %>
location.reload();